# Shopify App Configuration — Whanotify
# https://shopify.dev/docs/apps/tools/cli/configuration

name = "whanotify"
client_id = "d49a2d2c4e809e606dbae39770a3dcf3"
application_url = "https://whanotify.fly.dev"
embedded = true

[access_scopes]
scopes = "read_orders,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://whanotify.fly.dev/auth/callback"
]

[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

[pos]
embedded = false
